<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Staff Payroll System') }}
        </h2>
    </x-slot>

    <div class="py-8 bg-gray-50/50 min-h-screen">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
            @if(session('success'))
                <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded-2xl mb-4 font-bold">
                    {{ session('success') }}
                </div>
            @endif
            @if(session('error'))
                <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-2xl mb-4 font-bold">
                    {{ session('error') }}
                </div>
            @endif

            <div class="flex justify-between items-center bg-white p-6 rounded-[2rem] shadow-sm border border-gray-100">
                <h3 class="text-lg font-black text-gray-800 flex items-center gap-2">
                    <span class="w-1.5 h-6 bg-purple-500 rounded-full"></span>
                    Monthly Payroll Sheets
                </h3>
                <a href="{{ route('payrolls.create') }}" class="bg-purple-600 hover:bg-purple-700 text-white px-6 py-2 rounded-xl font-bold transition shadow-lg shadow-purple-200">
                    + Generate New Salary Sheet
                </a>
            </div>

            <div class="bg-white p-8 rounded-[2rem] shadow-sm border border-gray-100">
                <div class="overflow-x-auto">
                    <table class="w-full text-left">
                        <thead>
                            <tr class="text-[10px] font-black text-gray-400 uppercase tracking-widest border-b border-gray-50">
                                <th class="pb-3 pl-2">Month / Year</th>
                                <th class="pb-3">Total Amount</th>
                                <th class="pb-3">Status</th>
                                <th class="pb-3">Generated By</th>
                                <th class="pb-3 text-right pr-2">Actions</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-50">
                            @forelse($payrolls as $payroll)
                                <tr class="hover:bg-gray-50 transition-colors">
                                    <td class="py-4 pl-2 font-bold text-gray-800">
                                        {{ $payroll->month }} {{ $payroll->year }}
                                    </td>
                                    <td class="py-4 font-black text-green-600">
                                        ৳{{ number_format($payroll->total_amount, 2) }}
                                    </td>
                                    <td class="py-4">
                                        <span class="px-2 py-1 bg-yellow-100 text-yellow-700 rounded-md text-[10px] font-black uppercase">{{ $payroll->status }}</span>
                                    </td>
                                    <td class="py-4 text-sm text-gray-500 font-bold">
                                        {{ $payroll->createdBy->name ?? 'System' }}
                                    </td>
                                    <td class="py-4 text-right pr-2">
                                        <a href="{{ route('payrolls.show', $payroll->id) }}" class="text-purple-600 hover:text-purple-800 font-bold text-sm underline">
                                            View Master Sheet
                                        </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5" class="py-8 text-center text-gray-400 font-bold">
                                        No payroll sheets generated yet.
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
                <div class="mt-4">
                    {{ $payrolls->links() }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
